DROP TABLE IF EXISTS prices;

DROP TABLE IF EXISTS fanatical;
DROP TABLE IF EXISTS gamebillet;
DROP TABLE IF EXISTS gamesplanet;
DROP TABLE IF EXISTS gmg;
DROP TABLE IF EXISTS gog;
DROP TABLE IF EXISTS indiegala;
DROP TABLE IF EXISTS steam;
DROP TABLE IF EXISTS wgs;

DROP TABLE IF EXISTS drm;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS metadata;

DROP TABLE IF EXISTS bundles_fanatical;
DROP TABLE IF EXISTS bundles_steam;
DROP TABLE IF EXISTS bundles_indiegala;
